/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#ffb690',
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          DEFAULT: '#b9c7e0',
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        "on-secondary-fixed-variant": "#3a485c",
        "surface-container-low": "#131b2e",
        "surface-dim": "#0b1326",
        "surface-variant": "#2d3449",
        "error": "#ffb4ab",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed": "#c9e6ff",
        "inverse-primary": "#9d4300",
        "surface-container-lowest": "#060e20",
        "primary-fixed": "#ffdbca",
        "secondary-fixed-dim": "#b9c7e0",
        "inverse-on-surface": "#283044",
        "surface-container": "#171f33",
        "on-primary-fixed": "#341100",
        "on-primary-fixed-variant": "#783200",
        "text-vibrant": "#FFFFFF",
        "surface-container-high": "#222a3d",
        "on-surface": "#dae2fd",
        "surface-container-highest": "#2d3449",
        "primary-container": "#f97316",
        "background": "#0b1326",
        "on-error-container": "#ffdad6",
        "on-primary": "#552100",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb690",
        "tertiary-fixed-dim": "#89ceff",
        "surface": "#0b1326",
        "on-surface-variant": "#e0c0b1",
        "tertiary": "#89ceff",
        "surface-glass": "rgba(30, 41, 59, 0.7)",
        "on-tertiary-fixed": "#001e2f",
        "outline": "#a78b7d",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-secondary-container": "#abb9d2",
        "secondary-container": "#3c4a5e",
        "on-secondary-fixed": "#0d1c2f",
        "on-tertiary-container": "#003650",
        "on-tertiary": "#00344d",
        "on-primary-container": "#582200",
        "on-background": "#dae2fd",
        "outline-variant": "#584237",
        "on-secondary": "#233144",
        "surface-tint": "#ffb690",
        "secondary-fixed": "#d5e3fd",
        "text-muted": "#94A3B8",
        "border-subtle": "rgba(255, 255, 255, 0.1)",
        "tertiary-container": "#09a4e8",
        "surface-bright": "#31394d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "margin-desktop": "48px",
        "unit": "8px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "display-lg-mobile": ["36px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-xl": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-sm": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-xl-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}

